# Generated by Django 2.2 on 2019-11-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ordered_date',
            field=models.DateTimeField(default='2019-1-10'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipping_date',
            field=models.DateTimeField(default='2019-2-22'),
        ),
    ]
