# Generated by Django 2.2 on 2019-09-10 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactmessages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessages',
        ),
    ]
